### ISSUE TITLE
bosh deployment process hanged after vm created

### ISSUE THREAD

**Issue by SimyungYang** [cloudfoundry-incubator/bosh-softlayer-cpi-release#20] opened 2016-04-22 09:48 UTC
I'm trying to deploy bosh on softlayer with bosh-softlayer-cpi.
And bosh-init process got just hanged after vm created.
I checked that the bosh director vm is running and can be accessed by ssh protocol.
But monnit is not installed correctly.
I am not sure what mode the process in..
Do you guys have any idea?

I'm using the followings,
CPI : bosh-softlayer-cpi-12.tgz
bosh release: bosh-236+dev.12.tgz
stemcell: light-bosh-stemcell-3215-softlayer-esxi-ubuntu-trusty-go_agent.tgz

**Comment by mattcui** [comment] 2016-04-22 12:50
SimyungYang , please attach or send the deployment yaml to cuixuex@cn.ibm.com and wangjq@cn.ibm.com, don't expose your username/apikey. Thanks.

**Comment by SimyungYang** [comment] 2016-04-26 01:37
Matt Cui, Thank you for your quick response.
I've sent my yaml file to jian and wang.
Thank you,

**Comment by sykesm** [comment] 2016-06-01 16:03
I have hit this problem as well and discovered this issue. Since the issue is still open, I assume the problem hasn't been resolved?

Perhaps it's the undocumented requirement to be on the SoftLayer VPN when running bosh-init? Is the resolution simply to document that requirement?

Thanks.

/cc @maximilien

**Comment by mattcui** [comment] 2016-06-01 16:24
@sykesm Thanks for pointing it out, I added a note at the bottom of [Experimental bosh-init usage on SoftLayer](https://github.com/cloudfoundry-incubator/bosh-softlayer-cpi-release/blob/master/docs/bosh-init-usage.md)

**Comment by mattcui** [comment] 2016-06-02 16:52
I closed this issue, @SimyungYang, please open a new issue if you still have problems when deploying a director with our CPI. Thanks.

**Closed as completed by mattcui** 2016-06-02 16:52 UTC
Labels: bug

**Comment by SimyungYang** [comment] 2016-06-09 11:34
Yes, the problem was due to what @sykesm  pointed out above. 

The machine where bosh-init command was executed cannot connect to private ip of bosh director.

It was the problem..

Thank you, guys.

**Comment by maximilien** [comment] 2016-06-14 02:58
@mattcui and @jianqiu please ensure that the bosh.io docs include enough details and how to deal with this. Thx
